#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 32
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 5
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym__ = 2,
  sym__text = 3,
  sym__close_paragraph = 4,
  sym__block_close = 5,
  sym__div_marker_begin = 6,
  sym__div_marker_end = 7,
  sym__ignored = 8,
  sym_document = 9,
  sym__block = 10,
  sym_div = 11,
  sym_paragraph = 12,
  aux_sym__inline = 13,
  sym_emphasis = 14,
  sym__emphasis_begin = 15,
  sym__emphasis_end = 16,
  sym__fallback = 17,
  aux_sym_document_repeat1 = 18,
  aux_sym_paragraph_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym__] = "_",
  [sym__text] = "_text",
  [sym__close_paragraph] = "_close_paragraph",
  [sym__block_close] = "_block_close",
  [sym__div_marker_begin] = "div_marker",
  [sym__div_marker_end] = "div_marker",
  [sym__ignored] = "_ignored",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_div] = "div",
  [sym_paragraph] = "paragraph",
  [aux_sym__inline] = "_inline",
  [sym_emphasis] = "emphasis",
  [sym__emphasis_begin] = "_emphasis_begin",
  [sym__emphasis_end] = "_emphasis_end",
  [sym__fallback] = "_fallback",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym__] = anon_sym__,
  [sym__text] = sym__text,
  [sym__close_paragraph] = sym__close_paragraph,
  [sym__block_close] = sym__block_close,
  [sym__div_marker_begin] = sym__div_marker_begin,
  [sym__div_marker_end] = sym__div_marker_begin,
  [sym__ignored] = sym__ignored,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_div] = sym_div,
  [sym_paragraph] = sym_paragraph,
  [aux_sym__inline] = aux_sym__inline,
  [sym_emphasis] = sym_emphasis,
  [sym__emphasis_begin] = sym__emphasis_begin,
  [sym__emphasis_end] = sym__emphasis_end,
  [sym__fallback] = sym__fallback,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__close_paragraph] = {
    .visible = false,
    .named = true,
  },
  [sym__block_close] = {
    .visible = false,
    .named = true,
  },
  [sym__div_marker_begin] = {
    .visible = true,
    .named = true,
  },
  [sym__div_marker_end] = {
    .visible = true,
    .named = true,
  },
  [sym__ignored] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inline] = {
    .visible = false,
    .named = false,
  },
  [sym_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym__emphasis_begin] = {
    .visible = false,
    .named = true,
  },
  [sym__emphasis_end] = {
    .visible = false,
    .named = true,
  },
  [sym__fallback] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 3,
  [7] = 2,
  [8] = 4,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 15,
  [18] = 16,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 20,
  [24] = 21,
  [25] = 22,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 29,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\r') SKIP(1)
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym__text);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 4},
  [10] = {.lex_state = 0, .external_lex_state = 4},
  [11] = {.lex_state = 0, .external_lex_state = 4},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0, .external_lex_state = 5},
  [16] = {.lex_state = 0, .external_lex_state = 5},
  [17] = {.lex_state = 0, .external_lex_state = 6},
  [18] = {.lex_state = 0, .external_lex_state = 6},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 3},
  [24] = {.lex_state = 0, .external_lex_state = 3},
  [25] = {.lex_state = 0, .external_lex_state = 3},
  [26] = {.lex_state = 0, .external_lex_state = 4},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [sym__text] = ACTIONS(1),
    [sym__close_paragraph] = ACTIONS(1),
    [sym__block_close] = ACTIONS(1),
    [sym__div_marker_begin] = ACTIONS(1),
    [sym__div_marker_end] = ACTIONS(1),
    [sym__ignored] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(30),
    [sym__block] = STATE(5),
    [sym_div] = STATE(5),
    [sym_paragraph] = STATE(5),
    [aux_sym__inline] = STATE(12),
    [sym_emphasis] = STATE(12),
    [sym__emphasis_begin] = STATE(19),
    [sym__fallback] = STATE(12),
    [aux_sym_document_repeat1] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym__] = ACTIONS(7),
    [sym__text] = ACTIONS(9),
    [sym__div_marker_begin] = ACTIONS(11),
  },
  [2] = {
    [sym__block] = STATE(4),
    [sym_div] = STATE(4),
    [sym_paragraph] = STATE(4),
    [aux_sym__inline] = STATE(12),
    [sym_emphasis] = STATE(12),
    [sym__emphasis_begin] = STATE(19),
    [sym__fallback] = STATE(12),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_paragraph_repeat1] = STATE(10),
    [anon_sym_LF] = ACTIONS(13),
    [anon_sym__] = ACTIONS(7),
    [sym__text] = ACTIONS(9),
    [sym__block_close] = ACTIONS(15),
    [sym__div_marker_begin] = ACTIONS(17),
  },
  [3] = {
    [sym__block] = STATE(2),
    [sym_div] = STATE(2),
    [sym_paragraph] = STATE(2),
    [aux_sym__inline] = STATE(12),
    [sym_emphasis] = STATE(12),
    [sym__emphasis_begin] = STATE(19),
    [sym__fallback] = STATE(12),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(10),
    [anon_sym_LF] = ACTIONS(19),
    [anon_sym__] = ACTIONS(7),
    [sym__text] = ACTIONS(9),
    [sym__block_close] = ACTIONS(21),
    [sym__div_marker_begin] = ACTIONS(17),
  },
  [4] = {
    [sym__block] = STATE(4),
    [sym_div] = STATE(4),
    [sym_paragraph] = STATE(4),
    [aux_sym__inline] = STATE(12),
    [sym_emphasis] = STATE(12),
    [sym__emphasis_begin] = STATE(19),
    [sym__fallback] = STATE(12),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_paragraph_repeat1] = STATE(10),
    [anon_sym_LF] = ACTIONS(23),
    [anon_sym__] = ACTIONS(26),
    [sym__text] = ACTIONS(29),
    [sym__block_close] = ACTIONS(32),
    [sym__div_marker_begin] = ACTIONS(34),
  },
  [5] = {
    [sym__block] = STATE(8),
    [sym_div] = STATE(8),
    [sym_paragraph] = STATE(8),
    [aux_sym__inline] = STATE(12),
    [sym_emphasis] = STATE(12),
    [sym__emphasis_begin] = STATE(19),
    [sym__fallback] = STATE(12),
    [aux_sym_document_repeat1] = STATE(8),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(37),
    [anon_sym_LF] = ACTIONS(39),
    [anon_sym__] = ACTIONS(7),
    [sym__text] = ACTIONS(9),
    [sym__div_marker_begin] = ACTIONS(11),
  },
  [6] = {
    [sym__block] = STATE(7),
    [sym_div] = STATE(7),
    [sym_paragraph] = STATE(7),
    [aux_sym__inline] = STATE(12),
    [sym_emphasis] = STATE(12),
    [sym__emphasis_begin] = STATE(19),
    [sym__fallback] = STATE(12),
    [aux_sym_document_repeat1] = STATE(7),
    [aux_sym_paragraph_repeat1] = STATE(10),
    [anon_sym_LF] = ACTIONS(41),
    [anon_sym__] = ACTIONS(7),
    [sym__text] = ACTIONS(9),
    [sym__block_close] = ACTIONS(43),
    [sym__div_marker_begin] = ACTIONS(17),
  },
  [7] = {
    [sym__block] = STATE(4),
    [sym_div] = STATE(4),
    [sym_paragraph] = STATE(4),
    [aux_sym__inline] = STATE(12),
    [sym_emphasis] = STATE(12),
    [sym__emphasis_begin] = STATE(19),
    [sym__fallback] = STATE(12),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_paragraph_repeat1] = STATE(10),
    [anon_sym_LF] = ACTIONS(13),
    [anon_sym__] = ACTIONS(7),
    [sym__text] = ACTIONS(9),
    [sym__block_close] = ACTIONS(45),
    [sym__div_marker_begin] = ACTIONS(17),
  },
  [8] = {
    [sym__block] = STATE(8),
    [sym_div] = STATE(8),
    [sym_paragraph] = STATE(8),
    [aux_sym__inline] = STATE(12),
    [sym_emphasis] = STATE(12),
    [sym__emphasis_begin] = STATE(19),
    [sym__fallback] = STATE(12),
    [aux_sym_document_repeat1] = STATE(8),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(32),
    [anon_sym_LF] = ACTIONS(47),
    [anon_sym__] = ACTIONS(26),
    [sym__text] = ACTIONS(29),
    [sym__div_marker_begin] = ACTIONS(50),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(53), 1,
      anon_sym_LF,
    ACTIONS(55), 1,
      anon_sym__,
    ACTIONS(58), 1,
      sym__text,
    ACTIONS(61), 1,
      sym__close_paragraph,
    STATE(9), 1,
      aux_sym_paragraph_repeat1,
    STATE(19), 1,
      sym__emphasis_begin,
    STATE(12), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [24] = 7,
    ACTIONS(7), 1,
      anon_sym__,
    ACTIONS(9), 1,
      sym__text,
    ACTIONS(63), 1,
      anon_sym_LF,
    ACTIONS(65), 1,
      sym__close_paragraph,
    STATE(9), 1,
      aux_sym_paragraph_repeat1,
    STATE(19), 1,
      sym__emphasis_begin,
    STATE(12), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [48] = 7,
    ACTIONS(7), 1,
      anon_sym__,
    ACTIONS(9), 1,
      sym__text,
    ACTIONS(67), 1,
      anon_sym_LF,
    ACTIONS(69), 1,
      sym__close_paragraph,
    STATE(9), 1,
      aux_sym_paragraph_repeat1,
    STATE(19), 1,
      sym__emphasis_begin,
    STATE(12), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [72] = 5,
    ACTIONS(7), 1,
      anon_sym__,
    ACTIONS(71), 1,
      anon_sym_LF,
    ACTIONS(73), 1,
      sym__text,
    STATE(19), 1,
      sym__emphasis_begin,
    STATE(13), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [90] = 5,
    ACTIONS(75), 1,
      anon_sym_LF,
    ACTIONS(77), 1,
      anon_sym__,
    ACTIONS(80), 1,
      sym__text,
    STATE(19), 1,
      sym__emphasis_begin,
    STATE(13), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [108] = 5,
    ACTIONS(73), 1,
      sym__text,
    ACTIONS(83), 1,
      anon_sym__,
    STATE(19), 1,
      sym__emphasis_begin,
    STATE(27), 1,
      sym__emphasis_end,
    STATE(13), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [126] = 3,
    ACTIONS(89), 1,
      sym__div_marker_end,
    ACTIONS(85), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(87), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [139] = 3,
    ACTIONS(95), 1,
      sym__div_marker_end,
    ACTIONS(91), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(93), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [152] = 3,
    ACTIONS(97), 1,
      sym__div_marker_end,
    ACTIONS(85), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(87), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [165] = 3,
    ACTIONS(99), 1,
      sym__div_marker_end,
    ACTIONS(91), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(93), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [178] = 4,
    ACTIONS(7), 1,
      anon_sym__,
    ACTIONS(101), 1,
      sym__text,
    STATE(19), 1,
      sym__emphasis_begin,
    STATE(14), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [193] = 2,
    ACTIONS(103), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(105), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [203] = 2,
    ACTIONS(91), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(93), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [213] = 2,
    ACTIONS(107), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(109), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [223] = 2,
    ACTIONS(103), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(105), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [233] = 2,
    ACTIONS(91), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(93), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [243] = 2,
    ACTIONS(107), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(109), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [253] = 2,
    ACTIONS(61), 1,
      sym__close_paragraph,
    ACTIONS(53), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [262] = 1,
    ACTIONS(111), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [268] = 2,
    ACTIONS(113), 1,
      anon_sym_LF,
    ACTIONS(115), 2,
      anon_sym__,
      sym__text,
  [276] = 1,
    ACTIONS(118), 1,
      anon_sym_LF,
  [280] = 1,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
  [284] = 1,
    ACTIONS(122), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 24,
  [SMALL_STATE(11)] = 48,
  [SMALL_STATE(12)] = 72,
  [SMALL_STATE(13)] = 90,
  [SMALL_STATE(14)] = 108,
  [SMALL_STATE(15)] = 126,
  [SMALL_STATE(16)] = 139,
  [SMALL_STATE(17)] = 152,
  [SMALL_STATE(18)] = 165,
  [SMALL_STATE(19)] = 178,
  [SMALL_STATE(20)] = 193,
  [SMALL_STATE(21)] = 203,
  [SMALL_STATE(22)] = 213,
  [SMALL_STATE(23)] = 223,
  [SMALL_STATE(24)] = 233,
  [SMALL_STATE(25)] = 243,
  [SMALL_STATE(26)] = 253,
  [SMALL_STATE(27)] = 262,
  [SMALL_STATE(28)] = 268,
  [SMALL_STATE(29)] = 276,
  [SMALL_STATE(30)] = 280,
  [SMALL_STATE(31)] = 284,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(4),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(28),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(12),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(31),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(8),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(29),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(28),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(12),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inline, 2),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline, 2), SHIFT_REPEAT(28),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline, 2), SHIFT_REPEAT(13),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 4),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 4),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 5),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 5),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emphasis, 3),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fallback, 1, .dynamic_precedence = -100),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__emphasis_begin, 1), REDUCE(sym__fallback, 1, .dynamic_precedence = -100),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [120] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__close_paragraph = 0,
  ts_external_token__block_close = 1,
  ts_external_token__div_marker_begin = 2,
  ts_external_token__div_marker_end = 3,
  ts_external_token__ignored = 4,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__close_paragraph] = sym__close_paragraph,
  [ts_external_token__block_close] = sym__block_close,
  [ts_external_token__div_marker_begin] = sym__div_marker_begin,
  [ts_external_token__div_marker_end] = sym__div_marker_end,
  [ts_external_token__ignored] = sym__ignored,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__close_paragraph] = true,
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
    [ts_external_token__ignored] = true,
  },
  [2] = {
    [ts_external_token__div_marker_begin] = true,
  },
  [3] = {
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
  },
  [4] = {
    [ts_external_token__close_paragraph] = true,
  },
  [5] = {
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
  },
  [6] = {
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_sdjot_external_scanner_create(void);
void tree_sitter_sdjot_external_scanner_destroy(void *);
bool tree_sitter_sdjot_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_sdjot_external_scanner_serialize(void *, char *);
void tree_sitter_sdjot_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sdjot() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_sdjot_external_scanner_create,
      tree_sitter_sdjot_external_scanner_destroy,
      tree_sitter_sdjot_external_scanner_scan,
      tree_sitter_sdjot_external_scanner_serialize,
      tree_sitter_sdjot_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
