#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 31
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 5
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym__ = 2,
  sym__text = 3,
  sym__close_paragraph = 4,
  sym__block_close = 5,
  sym__div_marker_begin = 6,
  sym__div_marker_end = 7,
  sym__ignored = 8,
  sym_document = 9,
  sym__block = 10,
  sym_div = 11,
  sym_paragraph = 12,
  aux_sym__inline = 13,
  sym_emphasis = 14,
  sym__fallback = 15,
  aux_sym_document_repeat1 = 16,
  aux_sym_paragraph_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym__] = "_",
  [sym__text] = "_text",
  [sym__close_paragraph] = "_close_paragraph",
  [sym__block_close] = "_block_close",
  [sym__div_marker_begin] = "div_marker",
  [sym__div_marker_end] = "div_marker",
  [sym__ignored] = "_ignored",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_div] = "div",
  [sym_paragraph] = "paragraph",
  [aux_sym__inline] = "_inline",
  [sym_emphasis] = "emphasis",
  [sym__fallback] = "_fallback",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym__] = anon_sym__,
  [sym__text] = sym__text,
  [sym__close_paragraph] = sym__close_paragraph,
  [sym__block_close] = sym__block_close,
  [sym__div_marker_begin] = sym__div_marker_begin,
  [sym__div_marker_end] = sym__div_marker_begin,
  [sym__ignored] = sym__ignored,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_div] = sym_div,
  [sym_paragraph] = sym_paragraph,
  [aux_sym__inline] = aux_sym__inline,
  [sym_emphasis] = sym_emphasis,
  [sym__fallback] = sym__fallback,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__close_paragraph] = {
    .visible = false,
    .named = true,
  },
  [sym__block_close] = {
    .visible = false,
    .named = true,
  },
  [sym__div_marker_begin] = {
    .visible = true,
    .named = true,
  },
  [sym__div_marker_end] = {
    .visible = true,
    .named = true,
  },
  [sym__ignored] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inline] = {
    .visible = false,
    .named = false,
  },
  [sym_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym__fallback] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 3,
  [7] = 7,
  [8] = 4,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 12,
  [17] = 17,
  [18] = 14,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 20,
  [24] = 21,
  [25] = 25,
  [26] = 22,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 28,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\r') SKIP(1)
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym__text);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 3},
  [9] = {.lex_state = 0, .external_lex_state = 4},
  [10] = {.lex_state = 0, .external_lex_state = 4},
  [11] = {.lex_state = 0, .external_lex_state = 4},
  [12] = {.lex_state = 0, .external_lex_state = 5},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0, .external_lex_state = 6},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0, .external_lex_state = 6},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0, .external_lex_state = 5},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 3},
  [24] = {.lex_state = 0, .external_lex_state = 3},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 4},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [sym__text] = ACTIONS(1),
    [sym__close_paragraph] = ACTIONS(1),
    [sym__block_close] = ACTIONS(1),
    [sym__div_marker_begin] = ACTIONS(1),
    [sym__div_marker_end] = ACTIONS(1),
    [sym__ignored] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(29),
    [sym__block] = STATE(7),
    [sym_div] = STATE(7),
    [sym_paragraph] = STATE(7),
    [aux_sym__inline] = STATE(17),
    [sym_emphasis] = STATE(17),
    [sym__fallback] = STATE(17),
    [aux_sym_document_repeat1] = STATE(7),
    [aux_sym_paragraph_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym__] = ACTIONS(7),
    [sym__text] = ACTIONS(9),
    [sym__div_marker_begin] = ACTIONS(11),
  },
  [2] = {
    [sym__block] = STATE(2),
    [sym_div] = STATE(2),
    [sym_paragraph] = STATE(2),
    [aux_sym__inline] = STATE(17),
    [sym_emphasis] = STATE(17),
    [sym__fallback] = STATE(17),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(15),
    [anon_sym__] = ACTIONS(18),
    [sym__text] = ACTIONS(21),
    [sym__div_marker_begin] = ACTIONS(24),
  },
  [3] = {
    [sym__block] = STATE(5),
    [sym_div] = STATE(5),
    [sym_paragraph] = STATE(5),
    [aux_sym__inline] = STATE(17),
    [sym_emphasis] = STATE(17),
    [sym__fallback] = STATE(17),
    [aux_sym_document_repeat1] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym__] = ACTIONS(7),
    [sym__text] = ACTIONS(9),
    [sym__block_close] = ACTIONS(29),
    [sym__div_marker_begin] = ACTIONS(31),
  },
  [4] = {
    [sym__block] = STATE(3),
    [sym_div] = STATE(3),
    [sym_paragraph] = STATE(3),
    [aux_sym__inline] = STATE(17),
    [sym_emphasis] = STATE(17),
    [sym__fallback] = STATE(17),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [anon_sym_LF] = ACTIONS(33),
    [anon_sym__] = ACTIONS(7),
    [sym__text] = ACTIONS(9),
    [sym__block_close] = ACTIONS(35),
    [sym__div_marker_begin] = ACTIONS(31),
  },
  [5] = {
    [sym__block] = STATE(5),
    [sym_div] = STATE(5),
    [sym_paragraph] = STATE(5),
    [aux_sym__inline] = STATE(17),
    [sym_emphasis] = STATE(17),
    [sym__fallback] = STATE(17),
    [aux_sym_document_repeat1] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [anon_sym_LF] = ACTIONS(37),
    [anon_sym__] = ACTIONS(18),
    [sym__text] = ACTIONS(21),
    [sym__block_close] = ACTIONS(13),
    [sym__div_marker_begin] = ACTIONS(40),
  },
  [6] = {
    [sym__block] = STATE(5),
    [sym_div] = STATE(5),
    [sym_paragraph] = STATE(5),
    [aux_sym__inline] = STATE(17),
    [sym_emphasis] = STATE(17),
    [sym__fallback] = STATE(17),
    [aux_sym_document_repeat1] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym__] = ACTIONS(7),
    [sym__text] = ACTIONS(9),
    [sym__block_close] = ACTIONS(43),
    [sym__div_marker_begin] = ACTIONS(31),
  },
  [7] = {
    [sym__block] = STATE(2),
    [sym_div] = STATE(2),
    [sym_paragraph] = STATE(2),
    [aux_sym__inline] = STATE(17),
    [sym_emphasis] = STATE(17),
    [sym__fallback] = STATE(17),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(45),
    [anon_sym_LF] = ACTIONS(47),
    [anon_sym__] = ACTIONS(7),
    [sym__text] = ACTIONS(9),
    [sym__div_marker_begin] = ACTIONS(11),
  },
  [8] = {
    [sym__block] = STATE(6),
    [sym_div] = STATE(6),
    [sym_paragraph] = STATE(6),
    [aux_sym__inline] = STATE(17),
    [sym_emphasis] = STATE(17),
    [sym__fallback] = STATE(17),
    [aux_sym_document_repeat1] = STATE(6),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [anon_sym_LF] = ACTIONS(49),
    [anon_sym__] = ACTIONS(7),
    [sym__text] = ACTIONS(9),
    [sym__block_close] = ACTIONS(51),
    [sym__div_marker_begin] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(7), 1,
      anon_sym__,
    ACTIONS(9), 1,
      sym__text,
    ACTIONS(53), 1,
      anon_sym_LF,
    ACTIONS(55), 1,
      sym__close_paragraph,
    STATE(10), 1,
      aux_sym_paragraph_repeat1,
    STATE(17), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [21] = 6,
    ACTIONS(57), 1,
      anon_sym_LF,
    ACTIONS(59), 1,
      anon_sym__,
    ACTIONS(62), 1,
      sym__text,
    ACTIONS(65), 1,
      sym__close_paragraph,
    STATE(10), 1,
      aux_sym_paragraph_repeat1,
    STATE(17), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [42] = 6,
    ACTIONS(7), 1,
      anon_sym__,
    ACTIONS(9), 1,
      sym__text,
    ACTIONS(67), 1,
      anon_sym_LF,
    ACTIONS(69), 1,
      sym__close_paragraph,
    STATE(10), 1,
      aux_sym_paragraph_repeat1,
    STATE(17), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [63] = 3,
    ACTIONS(75), 1,
      sym__div_marker_end,
    ACTIONS(73), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(71), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [76] = 4,
    ACTIONS(77), 1,
      anon_sym_LF,
    ACTIONS(79), 1,
      anon_sym__,
    ACTIONS(82), 1,
      sym__text,
    STATE(13), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [91] = 3,
    ACTIONS(89), 1,
      sym__div_marker_end,
    ACTIONS(85), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(87), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [104] = 4,
    ACTIONS(91), 1,
      anon_sym_LF,
    ACTIONS(93), 1,
      anon_sym__,
    ACTIONS(97), 1,
      sym__text,
    STATE(25), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [119] = 3,
    ACTIONS(101), 1,
      sym__div_marker_end,
    ACTIONS(73), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(71), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [132] = 4,
    ACTIONS(7), 1,
      anon_sym__,
    ACTIONS(103), 1,
      anon_sym_LF,
    ACTIONS(105), 1,
      sym__text,
    STATE(13), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [147] = 3,
    ACTIONS(107), 1,
      sym__div_marker_end,
    ACTIONS(85), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(87), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [160] = 4,
    ACTIONS(109), 1,
      anon_sym_LF,
    ACTIONS(111), 1,
      anon_sym__,
    ACTIONS(114), 1,
      sym__text,
    STATE(25), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [175] = 2,
    ACTIONS(117), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(119), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [185] = 2,
    ACTIONS(73), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(71), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [195] = 2,
    ACTIONS(121), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(123), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [205] = 2,
    ACTIONS(117), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(119), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [215] = 2,
    ACTIONS(73), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(71), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [225] = 3,
    ACTIONS(105), 1,
      sym__text,
    ACTIONS(125), 1,
      anon_sym__,
    STATE(13), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [237] = 2,
    ACTIONS(121), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(123), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [247] = 2,
    ACTIONS(65), 1,
      sym__close_paragraph,
    ACTIONS(57), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [256] = 1,
    ACTIONS(127), 1,
      anon_sym_LF,
  [260] = 1,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
  [264] = 1,
    ACTIONS(131), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 21,
  [SMALL_STATE(11)] = 42,
  [SMALL_STATE(12)] = 63,
  [SMALL_STATE(13)] = 76,
  [SMALL_STATE(14)] = 91,
  [SMALL_STATE(15)] = 104,
  [SMALL_STATE(16)] = 119,
  [SMALL_STATE(17)] = 132,
  [SMALL_STATE(18)] = 147,
  [SMALL_STATE(19)] = 160,
  [SMALL_STATE(20)] = 175,
  [SMALL_STATE(21)] = 185,
  [SMALL_STATE(22)] = 195,
  [SMALL_STATE(23)] = 205,
  [SMALL_STATE(24)] = 215,
  [SMALL_STATE(25)] = 225,
  [SMALL_STATE(26)] = 237,
  [SMALL_STATE(27)] = 247,
  [SMALL_STATE(28)] = 256,
  [SMALL_STATE(29)] = 260,
  [SMALL_STATE(30)] = 264,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(2),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(19),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(17),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(28),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(5),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(30),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(19),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(17),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 4),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 4),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inline, 2),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline, 2), SHIFT_REPEAT(19),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline, 2), SHIFT_REPEAT(13),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emphasis, 3),
  [93] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback, 1), REDUCE(sym_emphasis, 3), SHIFT(19),
  [97] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback, 1), REDUCE(sym_emphasis, 3), SHIFT(25),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fallback, 1),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback, 1), SHIFT(19),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback, 1), SHIFT(25),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 5),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 5),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [129] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__close_paragraph = 0,
  ts_external_token__block_close = 1,
  ts_external_token__div_marker_begin = 2,
  ts_external_token__div_marker_end = 3,
  ts_external_token__ignored = 4,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__close_paragraph] = sym__close_paragraph,
  [ts_external_token__block_close] = sym__block_close,
  [ts_external_token__div_marker_begin] = sym__div_marker_begin,
  [ts_external_token__div_marker_end] = sym__div_marker_end,
  [ts_external_token__ignored] = sym__ignored,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__close_paragraph] = true,
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
    [ts_external_token__ignored] = true,
  },
  [2] = {
    [ts_external_token__div_marker_begin] = true,
  },
  [3] = {
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
  },
  [4] = {
    [ts_external_token__close_paragraph] = true,
  },
  [5] = {
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
  },
  [6] = {
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_sdjot_external_scanner_create(void);
void tree_sitter_sdjot_external_scanner_destroy(void *);
bool tree_sitter_sdjot_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_sdjot_external_scanner_serialize(void *, char *);
void tree_sitter_sdjot_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sdjot() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_sdjot_external_scanner_create,
      tree_sitter_sdjot_external_scanner_destroy,
      tree_sitter_sdjot_external_scanner_scan,
      tree_sitter_sdjot_external_scanner_serialize,
      tree_sitter_sdjot_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
